branches:
  only:
    - master
language: ruby
cache: bundler
before_install:
  - unset _JAVA_OPTIONS
  - gem install bundler
sudo: false
gemfile:
  - gemfiles/standalone.gemfile
  - gemfiles/binding_of_caller.gemfile
  - gemfiles/delayed_job.gemfile
  - gemfiles/rack_1.gemfile
  - gemfiles/rack.gemfile
  - gemfiles/sinatra_1.gemfile
  - gemfiles/sinatra.gemfile
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.0.gemfile
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails.gemfile
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.1.gemfile
rvm:
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - jruby-9.1.4.0
matrix:
  fast_finish: true
  allow_failures:
    - rvm: 2.2.6
      gemfile: gemfiles/rails.gemfile
    - rvm: 2.3.3
      gemfile: gemfiles/rails.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/rails.gemfile
    - rvm: jruby-9.1.4.0
      gemfile: gemfiles/rails.gemfile
  exclude:
    - rvm: 2.1.10
      gemfile: gemfiles/rails.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails5.0.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails5.1.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rack.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/sinatra.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/rails4.0.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/rails4.1.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/rails4.2.gemfile
    - rvm: jruby-9.1.4.0
      gemfile: gemfiles/binding_of_caller.gemfile
env:
  global:
    secure: DwQI6QHuRRaMoKvE9rnXmw3U1KLKH6Y1ZTXCcDN34Zkq7QG5KPt195zvL6XPbsefvd2fOHq4es5D6jxgLlEdKB7njhWX8XNMgb/eprz6zTxSAS/ep31zYHEJ3krWSPM6a7fXJOjdYIzXhVl7I0NRDZGy/Sf6LgHIBMpaGVKGc34=
notifications:
  slack:
    secure: FeZure+83NSqi7tPO7u/HZfOBORPyiWzTE7Hl1ddQDHOUtmWxLT82AlkMw+ZRbYms9MLJhitVwLbyFDdF8JOgyLcH0OAd7ZYglo08oPKS6NsupNW+knuXmYv8IJpqSo7kcr2Afs5F/atQEzX7spk3uqCwJOKIOypAJfJ4huZ3vE=
