branches:
  only:
    - master
language: ruby
cache: bundler
before_install:
  - unset _JAVA_OPTIONS
  - gem install bundler --version 1.16.0
sudo: false
gemfile:
  - gemfiles/standalone.gemfile
  - gemfiles/binding_of_caller.gemfile
  - gemfiles/delayed_job.gemfile
  - gemfiles/rack_1.gemfile
  - gemfiles/rack.gemfile
  - gemfiles/sinatra_1.gemfile
  - gemfiles/sinatra.gemfile
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails.gemfile
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.1.gemfile
  - gemfiles/rails5.2.gemfile
rvm:
  - 2.3.3
  - 2.4.0
  - 2.5.0
  - jruby-9.2.5.0
matrix:
  fast_finish: true
  allow_failures:
    - rvm: 2.3.3
      gemfile: gemfiles/rails.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/rails.gemfile
    - rvm: 2.5.0
      gemfile: gemfiles/rails.gemfile
    - rvm: jruby-9.2.5.0
      gemfile: gemfiles/rails.gemfile
  exclude:
    - rvm: 2.4.0
      gemfile: gemfiles/rails4.2.gemfile
    - rvm: 2.5.0
      gemfile: gemfiles/rails4.2.gemfile
    - rvm: jruby-9.2.5.0
      gemfile: gemfiles/binding_of_caller.gemfile
    - rvm: jruby-9.2.5.0
      gemfile: gemfiles/rails4.2.gemfile
env:
  global:
    secure: DwQI6QHuRRaMoKvE9rnXmw3U1KLKH6Y1ZTXCcDN34Zkq7QG5KPt195zvL6XPbsefvd2fOHq4es5D6jxgLlEdKB7njhWX8XNMgb/eprz6zTxSAS/ep31zYHEJ3krWSPM6a7fXJOjdYIzXhVl7I0NRDZGy/Sf6LgHIBMpaGVKGc34=
notifications:
  slack:
    secure: FeZure+83NSqi7tPO7u/HZfOBORPyiWzTE7Hl1ddQDHOUtmWxLT82AlkMw+ZRbYms9MLJhitVwLbyFDdF8JOgyLcH0OAd7ZYglo08oPKS6NsupNW+knuXmYv8IJpqSo7kcr2Afs5F/atQEzX7spk3uqCwJOKIOypAJfJ4huZ3vE=
